// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"time"
)

type User struct {
	ID             int64     `json:"id"`
	FullName       string    `json:"full_name"`
	Email          string    `json:"email"`
	Role           int32     `json:"role"`
	HashedPassword string    `json:"hashed_password"`
	CreatedAt      time.Time `json:"created_at"`
}
